In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
cd /content/drive/MyDrive/commit_test/collab_test

/content/drive/MyDrive/commit_test/collab_test


In [ ]:
!git config --global user.email '(qkrdbwls14@naver.com)'
!git config --global user.name '(YJinPark)'

In [ ]:
pwd

'/content/drive/MyDrive/commit_test/collab_test'

In [ ]:
!git add MLP기본.ipynb

In [ ]:
import tensorflow as tf
from tensorflow.keras import Model, layers
import numpy as np

## 딥러닝 모델

In [ ]:
class NeuralNet(Model):
    def __init__(self, hidden_1, hidden_2, num_classes):
        super(NeuralNet, self).__init__()
        self.mlp1 = layers.Dense(hidden_1, activation=tf.nn.relu)
        self.mlp2 = layers.Dense(hidden_2, activation="relu") # 둘 다 사용 가능
        self.mlp3 = layers.Dense(num_classes) # actiavtion="softmax"

    def call(self, x):
        print('x:',x.shape)
        x = self.mlp1(x)
        print('x2:',x.shape)
        x = self.mlp2(x)
        print('x3:',x.shape)
        x = self.mlp3(x)
        print('x4:',x.shape)
        x = tf.nn.softmax(x)
        return x

In [ ]:
hidden_1 = 128
hidden_2 = 256
num_classes = 10

In [ ]:
model = NeuralNet(hidden_1, hidden_2, num_classes)

In [ ]:
data = tf.random.normal(shape=(1,28*28), mean=0., stddev=1.)
print('data:', data.shape)
print('-'*40)

pred = model(data)
print('pred:', pred)
print('-'*40)

y_hat = tf.argmax(pred, 1)
print('y hat:', y_hat)

data: (1, 784)
----------------------------------------
x: (1, 784)
x2: (1, 128)
x3: (1, 256)
x4: (1, 10)
pred: tf.Tensor(
[[0.0996296  0.03623344 0.03637722 0.06330157 0.01717176 0.17229842
  0.0335761  0.09792687 0.08198035 0.36150467]], shape=(1, 10), dtype=float32)
----------------------------------------
y hat: tf.Tensor([9], shape=(1,), dtype=int64)


### layers.Dense

In [ ]:
x = tf.random.normal(shape=(3,28,28), mean=0., stddev=1.)

Without activation function

In [ ]:
fc_layer = layers.Dense(100)
x_after_fc = fc_layer(tf.reshape(x,(-1,28*28)))
print('x_after_fc:',x_after_fc.shape)
print(x_after_fc[0][:10])

x_after_fc: (3, 100)
tf.Tensor(
[ 1.9936794  -1.1581218  -1.5947511  -1.1529717   0.8168639   0.49706846
 -0.24799287 -1.1288154   0.2885541  -0.6473465 ], shape=(10,), dtype=float32)


With activation function

In [ ]:
fc_layer = layers.Dense(100, activation='relu')
x_after_fc = fc_layer(tf.reshape(x,(-1,28*28)))
print('x_after_fc:',x_after_fc.shape)
print(x_after_fc[0][:10])

x_after_fc: (3, 100)
tf.Tensor(
[0.         0.         3.0491018  0.         0.         0.6738207
 0.         1.6051943  0.21658832 0.        ], shape=(10,), dtype=float32)


### Softmax

In [ ]:
x = tf.random.normal(shape=(1,10), mean=0., stddev=1.)
x

<tf.Tensor: shape=(1, 10), dtype=float32, numpy=
array([[ 0.10717211,  2.0753634 , -0.6254686 , -0.52119464,  2.1069844 ,
         0.69352   , -1.1093087 , -1.1518859 ,  0.08022995,  0.8875352 ]],
      dtype=float32)>

In [ ]:
pred = tf.nn.softmax(x)
print('pred:',pred)
print('sum of pred:',tf.reduce_sum(pred))

pred: tf.Tensor(
[[0.04526367 0.3239846  0.02175545 0.02414646 0.334393   0.08135747
  0.01341031 0.01285132 0.04406045 0.09877729]], shape=(1, 10), dtype=float32)
sum of pred: tf.Tensor(1.0, shape=(), dtype=float32)


### tf.keras.Sequential

In [ ]:
class NeuralNet(Model):
    def __init__(self, hidden_1, hidden_2, num_classes):
        super(NeuralNet, self).__init__()
        self.fc1 = layers.Dense(hidden_1, activation=tf.nn.relu)
        self.fc2 = layers.Dense(hidden_2, activation=tf.nn.relu)
        self.out = layers.Dense(num_classes)

    def call(self, x):
        x = self.fc1(x)
        x = self.fc2(x)
        x = self.out(x)
        x = tf.nn.softmax(x)
        return x

In [ ]:
hidden_1 = 128
hidden_2 = 256
num_classes = 10

model = NeuralNet(hidden_1, hidden_2, num_classes)

In [ ]:
class NeuralNet2(Model):
    def __init__(self, hidden_1, hidden_2, num_classes):
        super(NeuralNet2, self).__init__()
        sequential = tf.keras.Sequential([
            layers.Dense(hidden_1, activation=tf.nn.relu),
            layers.Dense(hidden_2, activation=tf.nn.relu),
            layers.Dense(num_classes, activation=tf.nn.softmax),
        ])

    def call(self, x):
        x = sequential(x)
        return x

In [ ]:
hidden_1 = 128
hidden_2 = 256
num_classes = 10

model = NeuralNet2(hidden_1, hidden_2, num_classes)

### Sequential + add

In [ ]:
model = tf.keras.Sequential()

In [ ]:
model.add(layers.Dense(128, activation='relu'))
model.add(layers.Dense(256, activation='relu'))
model.add(layers.Dense(10, activation='softmax'))

### Compile

In [ ]:
model.compile(loss='categorical_crossentropy', # labels가 one-hot일 경우 사용
              optimizer='sgd',
              metrics=['accuracy'])

In [ ]:
model.compile(loss='sparse_categorical_crossentropy', # labels가 integer일 경우 사용
              optimizer='adam',
              metrics=['accuracy'])

In [ ]:
model.compile(loss='sparse_categorical_crossentropy',
              optimizer=tf.keras.optimizers.Adam(learning_rate=1e-3), # learning rate 설정
              metrics=['accuracy'])