In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
cd /content/drive/MyDrive/commit_test/collab_test

/content/drive/MyDrive/commit_test/collab_test


In [ ]:
!git config --global user.email '(qkrdbwls14@naver.com)'
!git config --global user.name '(YJinPark)'

In [ ]:
pwd

'/content/drive/MyDrive/commit_test/collab_test'

In [61]:
!git add MLP.ipynb

In [ ]:
import tensorflow as tf
from tensorflow.keras import Model, layers
import numpy as np

## 딥러닝 모델

In [ ]:
class NeuralNet(Model):
    def __init__(self, hidden_1, hidden_2, num_classes):
        super(NeuralNet, self).__init__()
        self.mlp1 = layers.Dense(hidden_1, activation=tf.nn.relu)
        self.mlp2 = layers.Dense(hidden_2, activation="relu") # 둘 다 사용 가능
        self.mlp3 = layers.Dense(num_classes) # actiavtion="softmax"

    def call(self, x):
        print('x:',x.shape)
        x = self.mlp1(x)
        print('x2:',x.shape)
        x = self.mlp2(x)
        print('x3:',x.shape)
        x = self.mlp3(x)
        print('x4:',x.shape)
        x = tf.nn.softmax(x)
        return x

In [ ]:
hidden_1 = 128
hidden_2 = 256
num_classes = 10

In [ ]:
model = NeuralNet(hidden_1, hidden_2, num_classes)

In [ ]:
data = tf.random.normal(shape=(1,28*28), mean=0., stddev=1.)
print('data:', data.shape)
print('-'*40)

pred = model(data)
print('pred:', pred)
print('-'*40)

y_hat = tf.argmax(pred, 1)
print('y hat:', y_hat)

data: (1, 784)
----------------------------------------
x: (1, 784)
x2: (1, 128)
x3: (1, 256)
x4: (1, 10)
pred: tf.Tensor(
[[0.04450556 0.02481987 0.06002142 0.0794529  0.08272821 0.06108548
  0.019853   0.19493954 0.07905077 0.35354322]], shape=(1, 10), dtype=float32)
----------------------------------------
y hat: tf.Tensor([9], shape=(1,), dtype=int64)


### layers.Dense

In [ ]:
x = tf.random.normal(shape=(3,28,28), mean=0., stddev=1.)

Without activation function

In [ ]:
fc_layer = layers.Dense(100)
x_after_fc = fc_layer(tf.reshape(x,(-1,28*28)))
print('x_after_fc:',x_after_fc.shape)
print(x_after_fc[0][:10])

x_after_fc: (3, 100)
tf.Tensor(
[ 1.5788283   0.50697815  3.229105    0.08917254 -1.0632293  -1.120286
 -1.0301162  -0.24175513  0.15965208  1.1792756 ], shape=(10,), dtype=float32)


With activation function

In [ ]:
fc_layer = layers.Dense(100, activation='relu')
x_after_fc = fc_layer(tf.reshape(x,(-1,28*28)))
print('x_after_fc:',x_after_fc.shape)
print(x_after_fc[0][:10])

x_after_fc: (3, 100)
tf.Tensor(
[0.21588632 0.9624751  0.         0.         0.8418823  0.
 1.487121   0.         0.900242   0.7475076 ], shape=(10,), dtype=float32)


### Softmax

In [ ]:
x = tf.random.normal(shape=(1,10), mean=0., stddev=1.)
x

<tf.Tensor: shape=(1, 10), dtype=float32, numpy=
array([[-0.5797538 ,  1.0401065 , -0.97650474, -0.2900029 , -0.01748445,
         1.3505965 ,  2.2290251 , -0.6890618 , -1.1413759 ,  1.3906871 ]],
      dtype=float32)>

In [ ]:
pred = tf.nn.softmax(x)
print('pred:',pred)
print('sum of pred:',tf.reduce_sum(pred))

pred: tf.Tensor(
[[0.02384485 0.12047336 0.01603569 0.03185898 0.04183936 0.1643369
  0.39557767 0.02137581 0.01359832 0.1710591 ]], shape=(1, 10), dtype=float32)
sum of pred: tf.Tensor(1.0, shape=(), dtype=float32)


### tf.keras.Sequential

In [ ]:
class NeuralNet(Model):
    def __init__(self, hidden_1, hidden_2, num_classes):
        super(NeuralNet, self).__init__()
        self.fc1 = layers.Dense(hidden_1, activation=tf.nn.relu)
        self.fc2 = layers.Dense(hidden_2, activation=tf.nn.relu)
        self.out = layers.Dense(num_classes)

    def call(self, x):
        x = self.fc1(x)
        x = self.fc2(x)
        x = self.out(x)
        x = tf.nn.softmax(x)
        return x

In [ ]:
hidden_1 = 128
hidden_2 = 256
num_classes = 10

model = NeuralNet(hidden_1, hidden_2, num_classes)

In [ ]:
class NeuralNet2(Model):
    def __init__(self, hidden_1, hidden_2, num_classes):
        super(NeuralNet2, self).__init__()
        sequential = tf.keras.Sequential([
            layers.Dense(hidden_1, activation=tf.nn.relu),
            layers.Dense(hidden_2, activation=tf.nn.relu),
            layers.Dense(num_classes, activation=tf.nn.softmax),
        ])

    def call(self, x):
        x = sequential(x)
        return x

In [ ]:
hidden_1 = 128
hidden_2 = 256
num_classes = 10

model = NeuralNet2(hidden_1, hidden_2, num_classes)

### Sequential + add

In [ ]:
model = tf.keras.Sequential()

In [ ]:
model.add(layers.Dense(128, activation='relu'))
model.add(layers.Dense(256, activation='relu'))
model.add(layers.Dense(10, activation='softmax'))

### Compile

In [ ]:
model.compile(loss='categorical_crossentropy', # labels가 one-hot일 경우 사용
              optimizer='sgd',
              metrics=['accuracy'])

In [ ]:
model.compile(loss='sparse_categorical_crossentropy', # labels가 integer일 경우 사용
              optimizer='adam',
              metrics=['accuracy'])

In [ ]:
model.compile(loss='sparse_categorical_crossentropy',
              optimizer=tf.keras.optimizers.Adam(learning_rate=1e-3), # learning rate 설정
              metrics=['accuracy'])